/**
 * Long-form in-app user guide embedded in the BYOL assistant system prompt.
 * Keep aligned with real UI labels and flows (see `App.tsx`, `PlanSidebar.tsx`,
 * `ActivationView.tsx`, `SettingsView.tsx`, `AiAssistantPanel.tsx`).
 *
 * Human-readable mirror: `docs/adoption-plan-user-guide.md` (short pointer only).
 */
export const ADOPTION_PLAN_ASSISTANT_USER_GUIDE = [
  '### Adoption Plan — detailed user guide (CSE / customer)',
  '',
  '#### 1. What this app is',
  'The **Adoption Plan** web app helps Cribl field teams capture a customer’s **Stream** and **Edge** rollout design: worker groups, fleets, data sources, rough volumes, and how data flows. The canonical handoff remains a **styled Excel (.xlsx)** aligned to Cribl’s **v0.9.1** adoption-plan gold template (`public/adoption-plan-empty.xlsx`). The UI edits structured **PlanState** in the browser; **Export** writes that state back into the workbook shell.',
  '',
  '#### 2. Screen layout (desktop)',
  '- **Left rail:** Plan navigation (expand/collapse), Worker Groups (Stream), Fleets (Edge), Sources list, Import, Export, **Settings**, **Reset Plan**. Drag the right edge of the rail to resize.',
  '- **Center:** Main content for the selected view (scrollable).',
  '- **Right rail (lg+):** **AI ASSISTANT** — collapsible strip; drag its **left** edge to resize (width is saved like the plan sidebar). Uses a JSON **plan digest** of the current plan plus embedded reference text (this guide, UI map, PS worksheet definitions). Optional tools search **criblpacks** on GitHub and **docs.cribl.io** indexes.',
  '- **Top header:** “Adoption Plan” title, build **version**, and **Customer** name (plan-wide).',
  '- **Narrow screens:** A **sticky horizontal nav** under the header exposes the same destinations as the left rail when the full sidebar is hidden.',
  '',
  '#### 3. Plan dashboard (sidebar → **Plan**)',
  'Default landing. Shows initiative / hero content, **topology or resource map** (depending on layout), paths into worker groups and fleets, **Source Summary** integration, **CSE notes** area, and an **Activation** callout when no PS tier is set (“Plan in shape? Activate it.”). Once a tier exists, a compact tier strip can appear instead. Use this page for executive orientation before drilling into rows.',
  '',
  '#### 4. Plan → **Summary**',
  '**Executive readout** — full inventory of worker groups / fleets and every source row (with GB/d, Stream/Edge column, tile, blockers), plus stakeholder narrative and provenance. Read-only relative to the structured editors. **Download summary (.md)** and **Download sources inventory (.xlsx)** (single-sheet source table) live on this page. For the full v0.9.1 adoption-plan workbook, use **Export** in the sidebar (below **Import**).',
  '',
  '#### 5. Plan → **Activation** (PS Use Case Worksheet UI)',
  'Mirrors the Excel sheet **PS Use Case Worksheet**. Three tabs (only one visible at a time):',
  '',
  '**5a. Header — PS tier**',
  '- Listbox: **Silver**, **Gold**, **Platinum**, or **Pick tier…** (unset). Colored dot matches tier.',
  '- Helper text always explains **how many of the five use-case slots** are in scope; tier **does not** remove any of the five **Base Scope** checklist rows.',
  '- **Silver:** first **2** use-case slots in scope in the UI/export gating. **Gold:** **3**. **Platinum:** all **5**. Unset tier: UI still shows all five slots at full opacity until a tier is chosen.',
  '',
  '**5b. Tab — Base Scope**',
  '- **Five fixed deliverable rows** (same for every tier). Each row: deliverable label, **Status** (Not Started / In Progress / Pending Review / Complete), **Notes**, and an in-app description blurb under the row (same copy the assistant receives in the static PS block).',
  '',
  '**5c. Tab — Use Case Overview**',
  '- Five numbered slots (1.0 … 5.0). Each slot: pick a **Use Case** **kind** from the gold pick-list (e.g. Data Onboarding, Data Reduction, … Other). Only slots **in tier scope** show as first-class cards; higher tier reveals more.',
  '- Choosing a kind surfaces a longer description under the picker (same text as in the assistant static block).',
  '',
  '**5d. Tab — Use Case Worksheet**',
  '- Starts with **three anchor rows** labeled Base Scope — Primary Source / Primary Destination / Storage Location (parameters + status + notes).',
  '- Then **five use-case blocks** (Use Case #1 … #5). Each block: column A header includes the gold’s tier tag pattern; **five parameter rows** per block with Parameters / Status / Notes; parameter numbers display as `1.0`–`5.0` style labels per template.',
  '- Footer copy may note when slots are hidden due to tier — they return if the tier is raised.',
  '',
  '#### 6. Worker Groups (Stream)',
  'Sidebar section **Worker Groups**. Index lists every **Stream** worker group row; **+ Add Worker Group**; optional **sort** controls. Click a row → **Worker group detail**: metrics (ingest/egress, hosting, worker counts), **resource map** linking sources, and actions to add or open sources. Stream vs Edge is determined by the row’s **kind** field.',
  '',
  '#### 7. Fleets (Edge)',
  'Sidebar section **Fleets**. Same index/detail pattern for **Edge** fleets. Top-level fleets and **sub-fleets** (nested under a parent) are supported where the plan has `parentFleetId`. Sub-fleet creation flows from the parent context when offered.',
  '',
  '#### 8. Sources',
  '**Sources** index shows all `sourceSummary` rows; count badge in the nav. **+ Add source** adds a row and opens **Source detail** (or a post-add choice). **Source** name is the row identity (v0.9.1 dropped a separate display-name column). Attach each source to a **worker group** or **fleet**. The detail form includes adoption fields (tile, destinations, avg daily GB, blockers, collection path, Stream/Edge column, security/observability, pipeline use case, on-prem vs cloud, additional notes, etc.) — aligned to the workbook’s per-WG / per-Fleet sheets.',
  '- After add: **choice dialog** vs **guided wizard** vs **direct full form** depends on **Settings → After adding a source**.',
  '',
  '#### 9. Import',
  'Nav → **Import**. Load an **.xlsx** adoption plan that matches the expected v0.9.1 shape; importer reports issues in-page. **Import from diagnostic bundle** accepts a Cribl **`.tar.gz` / `.tgz`** diag archive and parses `groups/<id>/…/inputs.yml` (and Leader-scope `local/cribl/inputs.yml` outside `groups/`) offline (browser `DecompressionStream` + tar). **Cribl.Cloud** diagnostics are **Leader-centric** (not separate **per-worker / per-node** bundle flows like many self-managed installs); **Import from live tenant** when Leader APIs are available usually populates the plan most completely on Cloud. **Self-managed** Worker exports often populate explicit worker groups; Leader-only bundles may collapse to **Leader (global)** depending on what is in the tarball. When the app runs inside the **Cribl App Platform**, **Import from live tenant** may appear: reads Leader topology and **configured sources** from **`/m/{group}/system/inputs`** — replaces in-memory topology; routing is not imported; user should review before exporting. **Leader data scope:** `docs/tenant-import-leader-data.md`. **Diag scope:** `docs/diag-import.md`.',
  '',
  '#### 10. Export',
  'Nav → **Export**. Downloads a **styled** `.xlsx` built from the **gold shell** plus current **PlanState**. If no shell is in memory, the app tries to fetch `adoption-plan-empty.xlsx` next to the deployed `index.html`. Export routing may use ExcelJS in-place fill for v0.9.1.',
  '',
  '#### 11. Settings',
  'Nav → **Settings** (sidebar). Sections typically include:',
  '- **OpenAI API key (assistant)** — save your key here; in Cribl it is stored with the app. Local development keeps it in this browser. The **`__local__`** preview shell cannot save a key—use a deployed app instead.',
  '- **After adding a source** — Ask every time / Always guided entry / Always enter details myself.',
  '- **Plan dashboard prompts** — restore the Activation nudge after dismiss.',
  '- **Detail page card expansion** — whether Source / Worker Group detail cards start expanded.',
  '- **UI animations** — reduce motion preference.',
  '- **Reset Plan** — destructive reset after confirmation (separate from AI **Clear chat**).',
  '- **About this build** — version string for bug reports.',
  '- **Feedback & app support** — contact **mmolina@cribl.io** for app-specific issues, feedback, or concerns (see Settings).',
  '',
  '#### 12. AI ASSISTANT (right rail)',
  '- **Starter prompts** group suggestions (plan digest vs GitHub packs vs docs).',
  '- **Send** runs OpenAI `gpt-4o-mini` with tools; replies should cite **only** URLs returned by tools (see ⓘ tooltip for proxy / allowlist guidance).',
  '- **Clear chat** clears persisted messages for the current **plan chat id** (customer + rough plan shape hash) after an **in-app** confirm — not a browser `confirm`.',
  '- The assistant **cannot** change the workbook; it reads **digestCoverage** in the digest to know what is omitted (truncated sources list, no full cell dump).',
  '',
  '#### 13. Excel v0.9.1 workbook (high level)',
  'Reserved / static sheets include **`INSTRUCTIONS`**, **`PS Use Case Worksheet`**, **`Stream Overview`**, **`Edge Overview`**, and **`input_data`**. Per–worker-group sheets are typically named with a **`wg-`** prefix (Stream) and per–fleet sheets with **`fl-`** (Edge), resolved from row names with collision rules; an **unassigned** bucket sheet name exists for orphaned sources at export time.',
  'The **PS Use Case Worksheet** holds Activation blocks: base scope table, use-case overview kinds, then the large worksheet grid. The app’s Activation tabs map to those blocks.',
  '',
  '#### 14. Persistence (conceptual)',
  '**Installed Cribl App:** plan state is stored in the pack **KV** store (see product docs / AGENTS). **Standalone single-file HTML:** **localStorage**. Not live Leader telemetry unless the user ran **tenant import** — then digest **planProvenance** reflects that. **Diag import** is offline (parsed bundle only); provenance **`diag`**.',
  '',
  '#### 15. Plan provenance (`planProvenance` in digest JSON)',
  'Optional object describing how the current topology entered the app:',
  '- **`scratch`** — started empty or from defaults in the browser (normalized when missing on older KV blobs).',
  '- **`xlsx`** — loaded from an imported adoption-plan `.xlsx` (`capturedAt` / `note` may be set).',
  '- **`tenant`** — bootstrapped from **Import from live tenant** on the App Platform (`capturedAt` / harvest `note` may be set).',
  '- **`diag`** — bootstrapped from **Import from diagnostic bundle** (`.tar.gz` / `.tgz`); snapshot of YAML under `groups/<id>/local|default/cribl/` and Leader-scope `local/cribl/inputs.yml` in the archive — not live Leader APIs. What you see depends on **bundle contents** (e.g. self-managed Worker exports vs Leader-only or Cloud Leader-centric diags).',
  'The digest is still not live telemetry; tenant import snapshots what the harvest API returned at import time; diag import snapshots what was present in the bundle files.',
  '',
  '#### 16. PS / Activation status vocabulary',
  'Both **Base Scope** and worksheet rows use the same **Status** pick-list enforced by the gold template: **Not Started**, **In Progress**, **Pending Review**, **Complete**. Default for untouched rows matches the template’s shipped default (**Not Started**).',
  '',
  '#### 17. Gold use-case tier tags (export labels)',
  'Each use-case slot’s column-A banner in the worksheet is stamped with a **tier tag** derived from slot index (`PS_USE_CASE_TIERS` in code): slot 1–2 → Silver, 3 → Gold, 4–5 → Platinum in the gold labeling pattern. This is **template/export labeling**, not the customer’s selected PS tier picker value.',
  '',
  '#### 18. Reordering & sorting',
  'Sources and worker-group lists in the sidebar support **drag reorder** where enabled, plus **sort** actions (e.g. A–Z, by ingest) on sections that expose sort buttons. Export order follows the in-memory plan order after fills.',
  '',
  '#### 19. Destructive actions (human safety)',
  '- **Reset Plan** (sidebar): wipes the adoption plan in storage after an in-app confirm — unrelated to AI chat.',
  '- **Remove** worker group / source: separate confirm dialogs; removing a group may affect attached sources per app rules.',
  '',
  '#### 20. AI assistant troubleshooting (common)',
  '- **No API key:** open **Settings** here and paste your OpenAI key. If you’re on a deployed Cribl app and it still fails, ask a workspace admin to confirm outbound access to OpenAI (and doc search if used)—details in **AGENTS.md**.',
  '- **`__local__` shell:** assistant OpenAI path disabled in that dev shell — use a deployed installed app.',
  '- **401/403:** bad or missing key; **429 insufficient_quota:** OpenAI billing.',
  '- **Doc tool empty on raw `file://`:** doc fetches expect Vite dev proxy or Cribl iframe — use `npm run dev` / `npm run preview` or the packaged app.',
  '',
  '#### 21. Standalone vs App Platform (conceptual)',
  '- **Packaged `.tgz` on Cribl:** KV persistence, tenant import, platform proxies for AI.',
  '- **Single-file standalone HTML:** local persistence; no tenant import; **diag import** works offline from a bundle file; optional AI key in browser — see `docs/adoption-plan-tool-one-pager.md`.',
  '',
  '#### 22. How you (the assistant) should use this guide',
  '- Prefer this **User guide** + **App UI reference** + **PS static canonical copy** + **plan digest** for **any** “where do I…”, “what does this field mean in *this* app”, “how does UI relate to Excel”, or “what happens if I import / export” question.',
  '- Use **search_cribl_docs_llms** / **search_cribl_packs_github** when the user needs **Cribl product behavior**, versioned docs, or community packs — not for navigation inside this app.',
  '- Never fabricate doc URLs. If something is not covered here or in the digest, say what is unknown and suggest the user check the on-screen UI, export the workbook, or official Cribl documentation via tools.',
].join('\n')
