/**
 * v0.9.1 sheet-name helpers.
 *
 * Every Stream worker group exports as a `wg-<name>` sheet; every Edge
 * fleet exports as a `fl-<name>` sheet. The dash-prefixed namespaces are
 * disjoint so a Stream WG and an Edge fleet can share the same body name
 * (`wg-prod` and `fl-prod`) without colliding. The user-typed worker-
 * group / fleet name still has to be sanitized into something Excel will
 * accept as a sheet name (no `: \ / ? * [ ]`, ≤31 chars), and the result
 * has to be unique within the workbook (Excel rejects two sheets with
 * the same name, comparison is case-insensitive).
 *
 * Backwards compatibility: pre-v2.0.0 workbooks used `wg<name>` (no dash)
 * for Stream WGs and `fl<name>_fleet` (literal `_fleet` suffix auto-
 * appended by the exporter) for Edge fleets. The classifier below
 * accepts both legacy forms on import so existing customer exports
 * still round-trip; the exporter only ever emits the new dash form.
 *
 * This module is small on purpose — the layout / I/O code in
 * `planWorkbookLayout.ts`, `exportWorkbook.ts`, and `importWorkbook.ts`
 * all depend on these helpers, so it's worth keeping them in one easy-
 * to-test place.
 */

import type { WorkerGroupKind, WorkerGroupRow } from '../types/planTypes'
import {
  LEGACY_V091_FLEET_SHEET_SUFFIX,
  V091_FLEET_SHEET_PREFIX,
  V091_WG_SHEET_PREFIX,
} from './planWorkbookLayout'

/**
 * Excel hard limits on a worksheet name.
 *
 * Spec: a sheet name must be 1–31 chars, can't be `History` (case-
 * insensitive — Excel reserves it for the change-tracking feature), and
 * can't contain any of `: \ / ? * [ ]` or end with a single `'`. We mirror
 * Excel here so a workbook generated by the app opens cleanly in both
 * Excel and Google Sheets without renaming.
 */
const SHEET_NAME_MAX_LEN = 31
const RESERVED_SHEET_NAMES = new Set(['history'])
const ILLEGAL_CHARS_RE = /[:\\/?*[\]]/g

/**
 * Strip illegal characters from a user-typed name and trim it. Whitespace is
 * collapsed (Excel allows spaces in sheet names but the gold template uses
 * no-space identifiers, so we collapse runs of whitespace to a single space
 * for readability).
 *
 * Returns the cleaned name or an empty string if nothing usable remained.
 */
function cleanRawName(raw: string): string {
  return raw
    .replace(ILLEGAL_CHARS_RE, '')
    .replace(/\s+/g, ' ')
    .trim()
}

/**
 * Truncate `body` so the full sheet name (`prefix + body + suffix`) fits in
 * Excel's 31-char limit. Truncation keeps the head of the body — the tail
 * is the part most likely to be a counter / qualifier the user added later
 * ("Production Cluster A 2024-Q3" → "Production Cluster A 202").
 */
function truncateBody(prefix: string, body: string, suffix: string): string {
  const room = SHEET_NAME_MAX_LEN - prefix.length - suffix.length
  if (room <= 0) {
    return ''
  }
  return body.length <= room ? body : body.slice(0, room).trimEnd()
}

function prefixFor(kind: WorkerGroupKind): string {
  return kind === 'edge' ? V091_FLEET_SHEET_PREFIX : V091_WG_SHEET_PREFIX
}

/**
 * Build the raw, pre-uniqueness sheet name for a worker-group / fleet row.
 *
 * Stream WGs use prefix `wg-`. Edge fleets use prefix `fl-`. A row with
 * an empty `wg` field falls back to its kind-aware default identifier
 * (`wg-WorkerGroup` / `fl-Fleet`) so the exporter never has to write a
 * sheet named just `wg-` or `fl-`.
 *
 * No suffix is appended — pre-v2.0.0 the exporter auto-suffixed `_fleet`
 * on Edge sheet names, but the dash prefix already disambiguates Stream
 * from Edge, and the suffix made user-chosen fleet names look like a
 * code artifact (`apex` rendering as `flapex_fleet`). The legacy form
 * is still recognized on import — see `classifyV091SheetName`.
 */
export function rawSheetNameFor(row: WorkerGroupRow): string {
  const prefix = prefixFor(row.kind)
  const cleaned = cleanRawName(row.wg)
  const fallback = row.kind === 'edge' ? 'Fleet' : 'WorkerGroup'
  const body = truncateBody(prefix, cleaned || fallback, '')
  if (!body) {
    return `${prefix}${fallback}`.slice(0, SHEET_NAME_MAX_LEN)
  }
  return `${prefix}${body}`
}

/**
 * Disambiguate a raw sheet name against names already assigned in the
 * current workbook. Appends `-2`, `-3`, … until the result is unique. If
 * the disambiguation suffix would push the name past 31 chars, the body is
 * shortened to make room.
 *
 * Comparison is case-insensitive — Excel treats `WgDefault` and `wgdefault`
 * as the same sheet name.
 */
export function disambiguateSheetName(
  raw: string,
  taken: ReadonlySet<string>,
): string {
  const lc = (s: string) => s.toLowerCase()
  if (!taken.has(lc(raw)) && !RESERVED_SHEET_NAMES.has(lc(raw))) {
    return raw
  }
  for (let i = 2; i < 1000; i += 1) {
    const suffix = `-${i}`
    const trimmed =
      raw.length + suffix.length <= SHEET_NAME_MAX_LEN
        ? raw
        : raw.slice(0, SHEET_NAME_MAX_LEN - suffix.length).trimEnd()
    const candidate = `${trimmed}${suffix}`
    if (!taken.has(lc(candidate)) && !RESERVED_SHEET_NAMES.has(lc(candidate))) {
      return candidate
    }
  }
  return `${raw.slice(0, SHEET_NAME_MAX_LEN - 5)}-9999`
}

/**
 * Resolve a final sheet name for one worker-group / fleet row. Appends to
 * `taken` so the caller can iterate in order without each call seeing its
 * own output.
 */
export function resolveSheetNameFor(
  row: WorkerGroupRow,
  taken: Set<string>,
): string {
  const raw = rawSheetNameFor(row)
  const final = disambiguateSheetName(raw, taken)
  taken.add(final.toLowerCase())
  return final
}

/**
 * Resolve sheet names for every worker-group / fleet row in a plan in
 * stable order. Returns a Map keyed by the row's `id` so the exporter and
 * overview-rollup hyperlink emitter agree on which sheet to point at.
 *
 * `reservedSheetNames` lets the caller seed the `taken` set with names of
 * sheets that already exist in the shell template (`Stream Overview`,
 * `Edge Overview`, `INSTRUCTIONS`, `PS Use Case Worksheet`, `input_data`)
 * so a user-named worker group can never collide with one of those.
 */
export function resolveAllSheetNames(
  rows: readonly WorkerGroupRow[],
  reservedSheetNames: readonly string[] = [],
): Map<string, string> {
  const taken = new Set<string>(reservedSheetNames.map((s) => s.toLowerCase()))
  const out = new Map<string, string>()
  for (const row of rows) {
    out.set(row.id, resolveSheetNameFor(row, taken))
  }
  return out
}

/**
 * Reverse helper for the importer: classify a sheet name as a Stream
 * worker-group sheet, an Edge fleet sheet, or neither. Returns the
 * cleaned worker-group / fleet display name (without the prefix / legacy
 * suffix) so the importer can seed `WorkerGroupRow.wg` directly.
 *
 * Recognizes BOTH the v2.0.0+ form and the pre-v2.0.0 legacy form:
 *
 *   - new (preferred):  `wg-<name>`             → Stream WG `<name>`
 *   - new (preferred):  `fl-<name>`             → Edge fleet `<name>`
 *   - legacy:           `wg<name>` (no dash)    → Stream WG `<name>`
 *   - legacy:           `fl<name>_fleet`        → Edge fleet `<name>`
 *
 * The legacy `_fleet` suffix is stripped on import — it was an exporter
 * artifact, not a user-typed name fragment, so a fleet that exported as
 * `flapex_fleet` round-trips as fleet `apex` (re-exporting it now
 * produces the new `fl-apex` sheet name).
 *
 * Order of checks matters because the prefixes nest: a `fl-foo` matches
 * the new Edge form first; a `flfoo_fleet` matches the legacy Edge form;
 * only after both Edge branches miss do we fall through to the Stream
 * branches, which then split between new (`wg-`) and legacy (`wg`).
 *
 * Comparison is case-sensitive on the prefix / suffix to match the gold
 * template (`wg-default`, not `WG-default`).
 */
export function classifyV091SheetName(
  sheetName: string,
):
  | { kind: 'stream'; displayName: string }
  | { kind: 'edge'; displayName: string }
  | null {
  // Edge — new dash form: `fl-<name>`
  if (
    sheetName.startsWith(V091_FLEET_SHEET_PREFIX) &&
    sheetName.length > V091_FLEET_SHEET_PREFIX.length
  ) {
    return { kind: 'edge', displayName: sheetName.slice(V091_FLEET_SHEET_PREFIX.length) }
  }

  // Edge — legacy form: `fl<name>_fleet` (no dash, suffix-disambiguated)
  const legacyEdgePrefix = V091_FLEET_SHEET_PREFIX.slice(0, -1) // 'fl'
  if (
    sheetName.startsWith(legacyEdgePrefix) &&
    sheetName.endsWith(LEGACY_V091_FLEET_SHEET_SUFFIX) &&
    sheetName.length > legacyEdgePrefix.length + LEGACY_V091_FLEET_SHEET_SUFFIX.length
  ) {
    const body = sheetName.slice(
      legacyEdgePrefix.length,
      sheetName.length - LEGACY_V091_FLEET_SHEET_SUFFIX.length,
    )
    return { kind: 'edge', displayName: body }
  }

  // Stream — new dash form: `wg-<name>`
  if (
    sheetName.startsWith(V091_WG_SHEET_PREFIX) &&
    sheetName.length > V091_WG_SHEET_PREFIX.length
  ) {
    return { kind: 'stream', displayName: sheetName.slice(V091_WG_SHEET_PREFIX.length) }
  }

  // Stream — legacy form: `wg<name>` (no dash). Reject the bare `wg`
  // prefix with no body so we don't misclassify a sheet literally named
  // `wg`, but anything longer is a Stream WG.
  const legacyWgPrefix = V091_WG_SHEET_PREFIX.slice(0, -1) // 'wg'
  if (
    sheetName.startsWith(legacyWgPrefix) &&
    sheetName.length > legacyWgPrefix.length
  ) {
    return { kind: 'stream', displayName: sheetName.slice(legacyWgPrefix.length) }
  }

  return null
}
